### PR TITLE
weekly_weather_controller

### PR DESCRIPTION
**Pull request by Yneq**
這裡的API 是必選city, town
@router.get("/weather/{city_name}/{town_name}")
回傳4個天氣因子
Screenshot 2024-07-17 at 5 09 32 AM

另外那個city_towns 很奇怪，可能有刪除過再加回來連江縣？？？

### CODE REVIEW

**Comment by Yneq** [comment]
1. 改動API key置於.env, CWB_API_KEY = os.getenv('CWB_API_KEY')
2. 更新四個天氣因子
3. 刪除重覆API

**Comment by Yneq** [comment]
1. code增加responses (就如同圖片所示)
2. logic renew
    town_data = next((loc for loc in locations if loc["locationName"] == town_name), None)
            if town_data is None:    #此處原town_name更改為town_data

**Review by 54Laichu — APPROVED** [review]
LGTM

**Review by RaphaFang — APPROVED** [review]
Great!

**Pull request merged**
